(cl:defpackage dialogflow_ros-msg
  (:use )
  (:export
   "<DIALOGFLOWCONTEXT>"
   "DIALOGFLOWCONTEXT"
   "<DIALOGFLOWPARAMETER>"
   "DIALOGFLOWPARAMETER"
   "<DIALOGFLOWREQUEST>"
   "DIALOGFLOWREQUEST"
   "<DIALOGFLOWRESULT>"
   "DIALOGFLOWRESULT"
  ))

